#!/usr/bin/env python3
"""导出 MySQL 中指定前缀的建表语句，只执行只读查询。"""

from __future__ import annotations

import argparse
import getpass
import os
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="只读导出 MySQL 中 mes_ 前缀表的 CREATE TABLE 语句"
    )
    parser.add_argument("--host", default=os.getenv("MYSQL_HOST", "127.0.0.1"))
    parser.add_argument("--port", type=int, default=int(os.getenv("MYSQL_PORT", "3306")))
    parser.add_argument("--user", default=os.getenv("MYSQL_USER", "root"))
    parser.add_argument("--database", default=os.getenv("MYSQL_DATABASE"))
    parser.add_argument("--password", default=os.getenv("MYSQL_PASSWORD"))
    parser.add_argument("--prefix", default="mes_", help="表名前缀，默认 mes_")
    parser.add_argument("--out", default="mes_schema.sql", help="输出文件名")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if not args.database:
        raise SystemExit("请提供 --database，或设置 MYSQL_DATABASE 环境变量。")
    password = args.password if args.password is not None else getpass.getpass("MySQL 密码（不会显示）：")

    try:
        import mysql.connector
    except ImportError as error:
        raise SystemExit(
            "缺少依赖 mysql-connector-python，请先在 Python 环境中安装它。"
        ) from error

    connection = mysql.connector.connect(
        host=args.host,
        port=args.port,
        user=args.user,
        password=password,
        database=args.database,
    )
    cursor = connection.cursor()
    try:
        # 仅查询 information_schema，筛选真实数据表；不执行任何 INSERT/UPDATE/DDL。
        cursor.execute(
            """
            SELECT TABLE_NAME
            FROM information_schema.TABLES
            WHERE TABLE_SCHEMA = %s
              AND TABLE_TYPE = 'BASE TABLE'
              AND TABLE_NAME LIKE %s
            ORDER BY TABLE_NAME
            """,
            (args.database, f"{args.prefix}%"),
        )
        table_names = [row[0] for row in cursor.fetchall()]
        if not table_names:
            raise SystemExit(f"数据库 {args.database!r} 中没有找到前缀为 {args.prefix!r} 的表。")

        statements: list[str] = [
            "-- Drifty MySQL schema export",
            f"-- Database: {args.database}",
            f"-- Prefix: {args.prefix}",
            f"-- Tables: {len(table_names)}",
            "-- Generated by scripts/export_mes_schema.py (read-only queries only)",
            "",
        ]
        for table_name in table_names:
            # 表名来自 information_schema；反引号转义后作为 SHOW CREATE TABLE 的标识符。
            escaped_name = table_name.replace("`", "``")
            cursor.execute(f"SHOW CREATE TABLE `{escaped_name}`")
            row = cursor.fetchone()
            if not row or not row[1]:
                print(f"跳过：无法读取 {table_name}")
                continue
            create_sql = str(row[1]).rstrip().rstrip(";") + ";"
            statements.extend([f"-- {table_name}", create_sql, ""])

        output = Path(args.out)
        output.write_text("\n".join(statements), encoding="utf-8")
        print(f"已导出 {len(table_names)} 张表 → {output.resolve()}")
        print("现在可在 Drifty 的‘导入’页面上传这个 .sql 文件，再选择项目、版本和环境。")
    finally:
        cursor.close()
        connection.close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
